FORMAT: 1A
HOST: http://localhost:3000/api/v1

# Apiary Sample Project

It is a simple API allowing consumers to view members in team.

## Questions Collection [/members]

### List All Members [GET]

+ Response 200 (application/json; charset=utf-8)


        [
            {
                "id": "1105037",
                "email": "vishnu.tiwary@oracle.com",
                "fullName": "Vishnu Tiwary",
                "userName": "Vish"
            },
            {
                "id": "1105038",
                "email": "moulika.devi@oracle.com",
                "fullName": "Moulika Devi",
                "userName": "Moulika"
            }
        ]

